# Generated by Django 3.1.7 on 2021-04-05 19:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import table_orders.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Big Hall', max_length=60)),
                ('width', models.FloatField(validators=[table_orders.validators.biggerThanZero])),
                ('depth', models.FloatField(validators=[table_orders.validators.biggerThanZero])),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[table_orders.validators.biggerThanZero])),
                ('is_round', models.BooleanField()),
                ('x', models.FloatField(validators=[table_orders.validators.biggerThanZero])),
                ('y', models.FloatField(validators=[table_orders.validators.biggerThanZero])),
                ('width', models.FloatField(validators=[table_orders.validators.biggerThanZero])),
                ('height', models.FloatField(validators=[table_orders.validators.biggerThanZero])),
                ('seats_count', models.PositiveSmallIntegerField(validators=[table_orders.validators.biggerThanZero])),
                ('hall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='table_orders.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mail', models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('username', models.CharField(max_length=60, null=True, validators=[django.core.validators.RegexValidator('[a-zA-Zа-яА-Я].{1,60}')])),
                ('tables', models.ManyToManyField(to='table_orders.Table')),
            ],
        ),
    ]
